name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.71.2
          cache: true
          environments: py313

      - name: Build a binary wheel and a source tarball
        run: pixi run -e py313 build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
